---
title: "R Notebook"
output: html_notebook
---

```{r}
descriptions <- read.table("descriptions.csv", sep = '\t', header= TRUE, encoding = "utf-8")
annotators <- read.table("annotators.csv", sep = '\t', header= TRUE, encoding = "utf-8")
literal_stats <- read.table("literal_stats.csv", sep = '\t', header= TRUE)[1:31]
sentimental_stats <- read.table("sentimental_stats.csv", sep = '\t', header= TRUE)[1:31]

```

```{r}
library(colorspace)
coul <- c("#FFC20A","#0C7BDC","#9B1D20","#050404")
fill <- adjustcolor(coul,alpha=0.8)
bord <- sapply(coul, darken)
```

```{r}
stat_columns = c("variable","t","p_t-test","c","p_correlation") 
stat_columns_comp = c("variable",
                      "variable_comp",
                      "t-test_literal",
                      "p_t-test_literal",
                      "correlation_literal",
                      "p_correlation_literal",
                      "t-test_sentimental",
                      "p_t-test_sentimental",
                      "correlation_sentimental",
                      "p_correlation_sentimental")
summary_names = c("Min","Q1","Median","Mean","Q3","Max","SD","Var")
literal_names = paste(summary_names, "_literal", sep="")
sentimental_names = paste(summary_names, "_sentimental", sep="")

modes = c("literal","sentimental")

all_columns <- append(stat_columns,literal_names,1)
all_columns <- append(all_columns,sentimental_names,length(literal_names) + 1)

t_tests <- data.frame(matrix(nrow=0, ncol = length(all_columns)))
t_tests_comp <- data.frame(matrix(nrow=0, ncol = 6))

description_vars <- names(literal_stats)[3:31]

literal_stats$mode <- "literal"
sentimental_stats$mode <- "sentimental"

joined_stats <- rbind(literal_stats, sentimental_stats)
mode_colors  <-  ifelse(joined_stats$mode == "literal", coul[1], coul[2])
mode_shapes  <-  ifelse(joined_stats$mode == "literal", 15, 19)

for (title in description_vars){
  literalVariableName <- sprintf("%s_literal", title)
  sentimentalVariableName <- sprintf("%s_sentimental", title)
  literalColumn <- literal_stats[,title]
  sentimentalColumn <- sentimental_stats[,title]

  png(sprintf("plots/%s.png",title), 800, 800, type = 'cairo')
  boxplot(round(literalColumn,2), round(sentimentalColumn, 2),
    main = sprintf("%s, literal vs. sentimental descriptions", title),
    names = c("literal","sentimental"),
    xlab = "description mode",
    ylab = title,
    col = coul,
    bg=coul,
    pch=21,
    border = bord,
    cex.axis = 1.5,
    cex.main = 1.5,
    cex.lab = 1.5)
  text(x=1.5, y=fivenum(round(literalColumn,2)),labels=fivenum(round(literalColumn,2)), font=2)
  text(x=2.5, y=fivenum(round(sentimentalColumn, 2)),labels=fivenum(round(sentimentalColumn, 2)), font=2)
  dev.off()
  t <- t.test(literalColumn, sentimentalColumn)
  c <- cor.test(literalColumn, sentimentalColumn)
  summary_literal <- append(summary(literalColumn),c(sd(literalColumn),var(literalColumn)))
  summary_sentimental <- append(summary(sentimentalColumn),c(sd(sentimentalColumn),var(sentimentalColumn)))

  names(summary_literal)=literal_names
  names(summary_sentimental)=sentimental_names


  stat_vector = c(title,t$statistic,t$p.value,c$estimate,c$p.value)
  stat_vector <- append(stat_vector,summary_literal,1)
  stat_vector <- append(stat_vector,summary_sentimental,length(summary_literal) + 1)
  names(stat_vector)  <-  all_columns

  t_tests <- rbind(t_tests, stat_vector)

  for (title_comp in description_vars){
    if (title == title_comp || any(t_tests_comp[,1]==title_comp & t_tests_comp[,2]==title)) {
      next
    }
    literalColumn_comp <- literal_stats[,title_comp]
    sentimentalColumn_comp <- sentimental_stats[,title_comp]
    t_literal <- t.test(literalColumn, literalColumn_comp)
    c_literal <- cor.test(literalColumn, literalColumn_comp)

    t_sentimental <- t.test(sentimentalColumn, sentimentalColumn_comp)
    c_sentimental <- cor.test(sentimentalColumn, sentimentalColumn_comp)
    stat_vector_comp = c(title, title_comp,
                         t_literal$statistic, t_literal$p.value, c_literal$estimate, c_literal$p.value,
                         t_sentimental$statistic, t_sentimental$p.value, c_sentimental$estimate, c_sentimental$p.value)
    names(stat_vector_comp) <- stat_columns_comp
    t_tests_comp <- rbind(t_tests_comp, stat_vector_comp)

    png(sprintf("plots/%s_vs_%s_literal.png",title,title_comp), 800, 800, type = 'cairo')
  plot(data.frame(joined_stats[title],joined_stats[title_comp]),
    main = sprintf("%s vs. %s", title, title_comp),
    xlab = title,
    ylab = title_comp,
    col = mode_colors,
    pch=mode_shapes,
    cex=1.5,
    cex.axis = 1.5,
    cex.main = 1.5,
    cex.lab = 1.5)
  
  lines(lowess(data.frame(joined_stats[title],joined_stats[title_comp])), col = coul[3], lwd = 3)
  
  legend("topleft",
       legend = levels(factor(joined_stats$mode)),
       pch = c(15,19),
       cex=1.5,
       col = c(coul[1], coul[2]))
  dev.off()
  }

}
colnames(t_tests)=all_columns
colnames(t_tests_comp) <- stat_columns_comp
write.csv(t_tests,"surfaceStats.csv", row.names=FALSE)
write.csv(t_tests_comp,"surfaceStats_comp.csv", row.names=FALSE)
```


```{r}

annotator_vars_numeric <- names(annotators)[c(4,11,12,13)]
annotator_vars_nonNumeric <- names(annotators)[c(5,6,7,8,9,10,14,15)]

for (title in annotator_vars_numeric){
  column <- annotators[,title]

  png(sprintf("plots/%s.png",title), 400, 400, type = 'cairo')
  boxplot(column,
    main = sprintf("%s distribution", title),
    ylab = title,
    col = coul,
    bg=coul,
    pch=21,
    border = bord,
    cex.axis = 1.5,
    cex.main = 1.5,
    cex.lab = 1.5)
  text(x=1.3, y=fivenum(column),labels=fivenum(column), font=2)
  dev.off()
  summary <- summary(column)
}
```
