---
title: "R Notebook"
output: html_notebook
---

```{r}
descriptions <- read.table("descriptions.csv", sep = '\t', header= TRUE, encoding = "utf-8")
literal_stats <- read.table("literal_stats.csv", sep = '\t', header= TRUE)[1:31]
sentimental_stats <- read.table("sentimental_stats.csv", sep = '\t', header= TRUE)[1:31]
annotators <- read.table("annotators.csv", sep = '\t', header= TRUE, encoding = "utf-8")

```

```{r}
library(colorspace)
coul <- c("#FFC20A","#0C7BDC","#A72608","#134611")
fill <- adjustcolor(coul,alpha=0.8)
bord <- sapply(coul, darken)
library(RColorBrewer)
barPal <- brewer.pal(9,"Set1")
```

```{r}
stat_columns = c("variable","t","p_t-test","c","p_correlation") 
stat_columns_comp = c("variable",
                      "variable_comp",
                      "t-test_literal",
                      "p_t-test_literal",
                      "correlation_literal",
                      "p_correlation_literal",
                      "t-test_sentimental",
                      "p_t-test_sentimental",
                      "correlation_sentimental",
                      "p_correlation_sentimental")
summary_names = c("Min","Q1","Median","Mean","Q3","Max","SD","Var")
literal_names = paste(summary_names, "_literal", sep="")
sentimental_names = paste(summary_names, "_sentimental", sep="")

modes = c("literal","sentimental")

all_columns <- append(stat_columns,c(literal_names,sentimental_names,summary_names),1)

t_tests <- data.frame(matrix(nrow=0, ncol = length(all_columns)))
t_tests_comp <- data.frame(matrix(nrow=0, ncol = 6))

annotator_vars <- names(annotators)[4:15]
annotator_vars_numeric <- names(annotators)[c(4,11,12,13)]
annotator_vars_nonNumeric <- names(annotators)[c(5,6,7,8,9,10,14,15)]
annotator_stats <- data.frame()
description_vars <- c(names(literal_stats)[3:31],annotator_vars_numeric, names(descriptions)[8])

literal_stats$mode <- "literal"
sentimental_stats$mode <- "sentimental"

literal_stats$annotator <- descriptions$annotator[descriptions$X_id==literal_stats$X_id]
sentimental_stats$annotator <- descriptions$annotator[descriptions$X_id==sentimental_stats$X_id]

library(lubridate, warn.conflicts = FALSE)

literal_stats$timeTaken <- as.duration(hms(descriptions$timeTaken[descriptions$X_id==literal_stats$X_id]))
sentimental_stats$timeTaken <- as.duration(hms(descriptions$timeTaken[descriptions$X_id==sentimental_stats$X_id]))

# Set description times over 10 minutes to the mean description time
literal_stats$timeTaken[literal_stats$timeTaken>600] <- mean(literal_stats$timeTaken[literal_stats$timeTaken<=600])
sentimental_stats$timeTaken[sentimental_stats$timeTaken>600] <- mean(sentimental_stats$timeTaken[sentimental_stats$timeTaken<=600])


for (annotator_var in annotator_vars){
  literal_stats[annotator_var] <- annotators[,annotator_var][match(literal_stats$annotator,annotators$X_id)]
  sentimental_stats[annotator_var] <- annotators[,annotator_var][match(sentimental_stats$annotator,annotators$X_id)]
}

joined_stats <- rbind(literal_stats, sentimental_stats)


mode_colors  <-  ifelse(joined_stats$mode == "literal", coul[1], coul[2])
mode_shapes  <-  ifelse(joined_stats$mode == "literal", 15, 19)
```

Assumptions for pearson's correlation, inspired by Cohen(1988):

|correlation coefficient value|strength of correlation|
|:----------------------------|:----------------------|
|0.3 < \| r \| <= .5          |weak                   |
|0.5 < \| r \| <= .7          |moderate               |
|0.7 < \| r \| <= 1           |strong                 |

```{r}

for (title in description_vars){
  literalVariableName <- sprintf("%s_literal", title)
  sentimentalVariableName <- sprintf("%s_sentimental", title)
  literalColumn <- literal_stats[,title]
  sentimentalColumn <- sentimental_stats[,title]

  if(!title %in% annotator_vars_numeric){
  png(sprintf("plots/%s.png",title), 800, 800, type = 'cairo')
  boxplot(round(literalColumn,2), round(sentimentalColumn, 2),
    main = sprintf("%s, literal vs. sentimental descriptions", title),
    names = c("literal","sentimental"),
    xlab = "description mode",
    ylab = title,
    col = coul,
    bg=coul,
    pch=21,
    border = bord,
    cex.axis = 1.5,
    cex.main = 1.5,
    cex.lab = 1.5)
  text(x=1.5, y=fivenum(round(literalColumn,2)),labels=fivenum(round(literalColumn,2)), font=2)
  text(x=2.5, y=fivenum(round(sentimentalColumn, 2)),labels=fivenum(round(sentimentalColumn, 2)), font=2)
  dev.off()
  t <- t.test(literalColumn, sentimentalColumn)
  c <- cor.test(literalColumn, sentimentalColumn)
  summary_literal <- c(summary(literalColumn),sd(literalColumn),var(literalColumn))
  summary_sentimental <- c(summary(sentimentalColumn),sd(sentimentalColumn),var(sentimentalColumn))
  summary_joint <- c(summary(joined_stats[,title]),sd(joined_stats[,title]),var(joined_stats[,title]))

  names(summary_literal)=literal_names
  names(summary_sentimental)=sentimental_names
  names(summary_joint)=summary_names

  stat_vector = c(title,t$statistic,t$p.value,c$estimate,c$p.value)
  stat_vector <- append(stat_vector,c(summary_literal,summary_sentimental,summary_joint),1)
  names(stat_vector)  <-  all_columns

  t_tests <- rbind(t_tests, stat_vector)
  }
  for (title_comp in description_vars){
    if (title == title_comp) {
      next
    }
    literalColumn_comp <- literal_stats[,title_comp]
    sentimentalColumn_comp <- sentimental_stats[,title_comp]
    t_literal <- t.test(literalColumn, literalColumn_comp)
    c_literal <- cor.test(literalColumn, literalColumn_comp)

    t_sentimental <- t.test(sentimentalColumn, sentimentalColumn_comp)
    c_sentimental <- cor.test(sentimentalColumn, sentimentalColumn_comp)
    stat_vector_comp = c(title, title_comp,
                         t_literal$statistic, t_literal$p.value, c_literal$estimate, c_literal$p.value,
                         t_sentimental$statistic, t_sentimental$p.value, c_sentimental$estimate, c_sentimental$p.value)
    names(stat_vector_comp) <- stat_columns_comp
    t_tests_comp <- rbind(t_tests_comp, stat_vector_comp)

    png(sprintf("plots/%s_vs_%s.png",title,title_comp), 800, 800, type = 'cairo')
    plot(data.frame(joined_stats[title],joined_stats[title_comp]),
    main = sprintf("%s vs. %s", title, title_comp),
    xlab = title,
    ylab = title_comp,
    col = mode_colors,
    pch=mode_shapes,
    cex=1.5,
    cex.axis = 1.5,
    cex.main = 1.5,
    cex.lab = 1.5)
  

 
  # Plot smoothing lines if there is at least a weak correlation (r>0.3)
    if((abs(c_literal$estimate)>0.3)||(abs(c_literal$estimate)>0.3)){
      literalLineIndices <- Reduce(intersect, list(which(joined_stats$mode=="literal"),
                                                which(joined_stats[,title] > 0),
                                                which(joined_stats[,title_comp] > 0)))
      lines(lowess(data.frame(joined_stats[,title][literalLineIndices],
                            joined_stats[,title_comp][literalLineIndices], f=3)), 
                            col = "black", lty = 5, lwd = 3)
      sentimentalLineIndices <- Reduce(intersect, list(which(joined_stats$mode=="sentimental"),
                                                     which(joined_stats[,title] > 0),
                                                     which(joined_stats[,title_comp] > 0)))
      lines(lowess(data.frame(joined_stats[,title][sentimentalLineIndices],
                            joined_stats[,title_comp][sentimentalLineIndices], f=3)), 
                            col = "black", lty=3, lwd = 3)
      legendLevels <- levels(factor(joined_stats$mode))
      legendLevels[1] <- sprintf("%s, r = %.2f",legendLevels[1],c_literal$estimate)
      legendLevels[2] <- sprintf("%s, r = %.2f",legendLevels[2],c_sentimental$estimate)
      
      legend("topleft",
      legend = legendLevels,
      pch = c(NA,NA),
      cex=1.5,
      col = "black",
      lty = c(5,3),
      lwd = 3)
    }
  
  legend("topright",
       legend = levels(factor(joined_stats$mode)),
       pch = c(15,19),
       cex=1.5,
       col = c(coul[1], coul[2]))
  
  dev.off()
  }

}
colnames(t_tests)=all_columns
colnames(t_tests_comp) <- stat_columns_comp
write.csv(t_tests,"surfaceStats.csv", row.names=FALSE)
write.csv(t_tests_comp,"surfaceStats_comp.csv", row.names=FALSE)
```


```{r}
annotators$firstLanguage<-replace(annotators$firstLanguage, annotators$firstLanguage%in%c("de","deutsch","Deutsch"), "DE")
annotators$firstLanguage<-replace(annotators$firstLanguage, annotators$firstLanguage=="portugiesisch", "PT")
annotators$firstLanguage<-replace(annotators$firstLanguage, annotators$firstLanguage=="Arabisch", "AR")

annotators$nationality<-replace(annotators$nationality, annotators$nationality%in%c("de","deutsch","Deutsch"), "DE")
annotators$nationality<-replace(annotators$nationality, annotators$nationality=="Israelisch", "IL")
annotators$nationality<-replace(annotators$nationality, annotators$nationality=="Österreichisch", "AT")

for (title in annotator_vars_numeric){
  column <- annotators[,title]
  png(sprintf("plots/%s.png",title), 600, 600, type = 'cairo')
  par(mar=c(2,5,4,2) + 0.1) 
  boxplot(column,
    main = sprintf("%s distribution", title),
    ylab = title,
    col = coul,
    bg=coul,
    pch=21,
    border = bord,
    cex.axis = 2.0,
    cex.main = 2.5,
    cex.lab = 2.0)
  text(x=1.3, y=fivenum(column),labels=fivenum(column), cex=1.5, font=2)
  dev.off()
  summary <- summary(column)
  annotator_stats <- rbind(annotator_stats, summary)
  # write.csv(summary,"annotatorStats.csv", row.names=FALSE)
}

library("plyr")
for (title in annotator_vars_nonNumeric){
  column <- annotators[,title]
  max <- round_any(max(matrix(table(column))[,1]), 5, f = ceiling) 
  png(sprintf("plots/%s.png",title), 1000, 650, type = 'cairo')
  par(mar=c(5,30,4,2) + 0.1) # Add space to left margin.
  barplot(table(column)[order(table(column),decreasing = TRUE)],
    horiz = TRUE,
    xaxt = "n",
    las=2,
    main = title,
    col = barPal,
    bg=barPal,
    bord=NA,
    xlim = c(0, max),
    cex.axis = 2.5,
    cex.lab = 2.5,
    cex.main = 2.5,
    cex.names = 1.8
  )
  axis(1, at = seq(0, max,  1),labels=NA, cex.axis = 2.0)
  axis(1, at = seq(0, max,  5), lwd=3, cex.axis = 2.0)
  par(mar=c(5,4,4,2) + 0.1) # Restore default spacing
  dev.off()

}
```
